### PR TITLE
feat: Add Ddu:start autocmd

### PR DESCRIPTION
**Pull request by 4513ECHO**
SSIA

### CODE REVIEW

**Comment by Shougo** [comment]
Hm...

Why the event is needed?  Please describe it.

Because it does not check UI.

**Review by Shougo — CHANGES_REQUESTED** [review]
autocmd initialization is required like `Ddu:redraw`.

**Comment by Shougo** [comment]
`uiRedraw()` does not gurantee the UI window is created.

**Comment by 4513ECHO** [comment]
The autocmd is not needed actually.

**Pull request closed without merging**
