### PR TITLE
Better dependencies

### PR DESCRIPTION
**Pull request by Shougo**
Fix https://github.com/Shougo/ddu.vim/pull/121 imports.

### CODE REVIEW

**Comment by Shougo** [comment]
I have added `v6.0.0-pre1` tag.

**Comment by 4513ECHO** [comment]
Excellent.

```console
$ deno info jsr:@4513echo/ddu-kind-url@0.5.0 | head -4 # with jsr:@shougo/ddu-vim@5.0.0
local: /Users/user/Library/Caches/deno/deps/https/jsr.io/c6aee04005c0eb24a70dc67c08f7cd42e97e97cf55ddd76fead35ef94fe58b99
type: TypeScript
dependencies: 381 unique
size: 2.44MB
$ deno info jsr:@4513echo/ddu-kind-url@0.6.0-pre.0 | head -4 # with jsr:@shougo/ddu-vim@6.0.0-pre1
local: /Users/user/Library/Caches/deno/deps/https/jsr.io/b4412eb79db9b4ff964327273f52cbc96b27baf9aa6d6184b0eed52db2d40d8e
type: TypeScript
dependencies: 173 unique
size: 873.71KB
```

**Comment by 4513ECHO** [comment]
Please update `jsr:@denops/std` to v7.1.0

**Comment by Shougo** [comment]
Done.

**Comment by Shougo** [comment]
I have tested it and it works for me.

**Comment by Shougo** [comment]
OK.  I will merge it.

**Pull request merged**
