### PR TITLE
[RFC] Resolve circular reference of imports

### PR DESCRIPTION
**Pull request by 4513ECHO**
WIP

Need to discuss:
- Should we stop re-exporting `Base*` classes and `Base*Params` types from types.ts?
- Should we move definitions of `Base*Params` types to types.ts and import them from `base/*.ts`?

Current dependencies graph:

image

### CODE REVIEW

**Comment by 4513ECHO** [comment]
Ideal:

image

**Comment by Shougo** [comment]
> Should we stop re-exporting Base* classes and Base*Params types from types.ts?

It should.

> Should we move definitions of Base*Params types to types.ts and import them from base/*.ts?

It should not.

Because `base/*.ts` files are already exported.

**Comment by 4513ECHO** [comment]
We have stopped re-exporting, but the problem continues to persist.
types.ts defines `User{Column,Fiter,Source,Ui` which depends on `Base{Column,Filter,Source,Ui}Params`, so we cannot make types.ts independent.
To solve the problem we have to define `Base*Params` in types.ts in the same way that we do` BaseActionParams` in types.ts.

**Comment by Shougo** [comment]
Hm... If so, `User{Column, Filer, Source, Ui}` should be exported in `base/*.ts` files.

**Comment by 4513ECHO** [comment]
Oh, I have found `DduOptions` also depends on `Base*Params`.
Is there any way to keep `DduOptions` in types.ts other than defining `Base*Params` and `User*` in types.ts?

```ts
export type DduOptions = {
  // ...
  columnParams: Record<ColumnName, Partial<BaseColumnParams>>;
  filterParams: Record<FilterName, Partial<BaseFilterParams>>;
  kindParams: Record<KindName, Partial<BaseKindParams>>;
  // ...
  postFilters: UserFilter[];
  sourceParams: Record<SourceName, Partial<BaseSourceParams>>;
  sources: UserSource[];
  // ...
  uiParams: Record<UiName, Partial<BaseUiParams>>;
};
```

**Comment by Shougo** [comment]
`DduOptions` must be defined in `types.ts`.

Hm...

`Base*Params` can be defined in `BaseParams` in types.ts.
Because it is just `Record<string, unknown>`.

**Comment by 4513ECHO** [comment]
Remaining circular reference:

- `ddu.ts` and `types.ts`
- `context.ts` and `types.ts`
- `loader.ts` and `base/source.ts`

**Comment by 4513ECHO** [comment]
I think the following way is better to resolve a circular reference between `loader.ts` and `base/source/ts`:

1. Define `Loader` interface in `types.ts`.

```ts
export interface Loader {
  async initStaticImportPath(denops: Denops): Promise<void>;
  async autoload(denops: Denops, type: DduExtType, name: string): Promise<void>;
  registerAlias(type: DduAliasType, alias: string, base: string): void;
  async registerPath(type: DduExtType, path: string): Promise<void>;
  getUi(index: string, name: string): BaseUi<BaseParams> | null;
  getSource(index: string, name: string): BaseSource<BaseParams> | null;
  getFilter(index: string, name: string): BaseFilter<BaseParams> | null;
  getKind(index: string, name: string): BaseKind<BaseParams> | null;
  getColumn(index: string, name: string): BaseColumn<BaseParams> | null;
  getAlias(type: DduAliasType, name: string): string | undefined;
  getAliasNames(type: DduAliasType): string[];
  getSourceNames(): string[];
}
```

2. Implement the interface in `loader.ts`.

```ts
import type { Loader } from "./types.ts";

export class LoaderImpl implements Loader {
  // ...
}
```

3. Import `Loader` from `types.ts` in `base/source.ts`.

**Comment by Shougo** [comment]
> context.ts and types.ts

Hm.  

```typescript
export { ContextBuilder } from "./context.ts";
```

can be removed in `types.ts`.

> ddu.ts and types.ts

```
export type { Ddu } from "./ddu.ts";
```

can be removed in `types.ts`

**Comment by Shougo** [comment]
> loader.ts and base/source.ts

Hm...

`loader.ts` is only used for the arguments.

```typescript
export type OnInitArguments<Params extends BaseSourceParams> = {
  denops: Denops;
  sourceOptions: SourceOptions;
  sourceParams: Params;
  loader: Loader;
};

export type OnEventArguments<Params extends BaseSourceParams> = {
  denops: Denops;
  sourceOptions: SourceOptions;
  sourceParams: Params;
  event: DduEvent;
};

export type GatherArguments<Params extends BaseSourceParams> = {
  denops: Denops;
  context: Context;
  options: DduOptions;
  sourceOptions: SourceOptions;
  sourceParams: Params;
  input: string;
  parent?: DduItem;
  loader: Loader;
};
```

You can split the file.

**Comment by Shougo** [comment]
Why `base/source.ts` requires loader?
Because some sources uses loader...

**Comment by Shougo** [comment]
https://github.com/4513ECHO/ddu-source-source/blob/main/denops/%40ddu-sources/source.ts

Hm...  `ddu-source-source` uses the feature.

**Comment by 4513ECHO** [comment]
Remaining circular references:

1. `types.ts` and `base.ui.ts`
2. among `ext.ts`, `ddu.ts` and `base/ui.ts`

If we move the definition of `UiActionArguments` to `types.ts`, ① and ② is going to be resolved.
However, because of `UiActionArguments` depends on `Ddu`, a new circular reference between `types.ts` and `ddu.ts` is happening.

**Comment by 4513ECHO** [comment]
This dependency was added at https://github.com/Shougo/ddu.vim/commit/3202e53453d082cce9e829048d2c285864d5ceab. Why `UiActionArguments` requires `Ddu`?

**Comment by Shougo** [comment]
> This dependency was added at https://github.com/Shougo/ddu.vim/commit/3202e53453d082cce9e829048d2c285864d5ceab. Why UiActionArguments requires Ddu?

Because user actions want to use ddu like this.

```typescript
    args.contextBuilder.patchGlobal({
      ui: "ff",
      profile: false,
      uiOptions: {
        ff: {
          actions: {
            kensaku: async (args: {
              denops: Denops;
              ddu: Ddu;
            }) => {
              args.ddu.updateOptions({
                sourceOptions: {
                  _: {
                    matchers: ["matcher_kensaku"],
                  },
                },
              });
              await args.denops.cmd("echomsg 'change to kensaku matcher'");

              return ActionFlags.Persist;
            },
          },
        },
        filer: {
          toggle: true,
        },
      },
```

**Comment by 4513ECHO** [comment]
This pull request is now ready to use now.
@Shougo Could you release pre-release version to test?

Current dependencies graph:

image

**Comment by Shougo** [comment]
OK.

**Pull request closed without merging**
