### PR TITLE
include module path in `getXXX` returned values

### PR DESCRIPTION
**Pull request by gamoutatsumi**
https://github.com/Milly/ddu-filter-merge needs module path.

### CODE REVIEW

**Comment by Shougo** [comment]
Really?  I didn't think it is used...

**Comment by gamoutatsumi** [comment]
`getFilter` in `ddu/app.ts` used by here.

https://github.com/Milly/ddu-filter-merge/blob/ee60d679341eeecc597e7b4900f090527c1fd14e/denops/%40ddu-filters/merge.ts#L209-L220

**Comment by Shougo** [comment]
OK.  Merged.

**Comment by gamoutatsumi** [comment]
Thanks!

**Pull request merged**
